version: 2

models:
  - name: metrics
    schema: public
    description: "This table stores various metrics details with different measurement units and timestamps."

    columns:
      - name: componentname
        description: "The name of the component for which the metric is recorded."
        
      - name: fromtimestamp
        description: "The starting timestamp for the metric recording period."
        
      - name: maxvalue
        description: "The maximum value recorded for the metric in the specified time frame."
        tests:
          - not_null
          - maxvalue_test

      - name: metricname
        description: "The name of the metric."
        tests:
          - not_null

      - name: minvalue
        description: "The minimum value recorded for the metric in the specified time frame."
        tests:
          - not_null

      - name: totimestamp
        description: "The ending timestamp for the metric recording period."
        
      - name: unit
        description: "The unit of measurement for the metric."
        tests:
          - not_null